export function generateRandomName() {
  const adjectives = [
    'cerebral',
    'indelible',
    'euphonious',
    'austere',
    'sanguine',
    'jubilant',
    'imperturbable',
    'convivial',
    'erudite',
    'stoic',
    'pensive',
    'astounding',
    'incandescent',
    'exquisite',
    'somber',
    'voracious',
    'resilient',
    'unfathomable',
    'ephemeral',
    'melancholic',
    'serendipitous',
    'melodic',
    'kaleidoscopic',
    'tempestuous',
    'idyllic',
    'inscrutable',
    'confounding',
    'poignant',
    'luminous',
    'languid',
    'mellifluous',
    'verdant',
    'wistful',
    'ethereal',
    'scintillating',
    'precocious',
    'gregarious',
    'diaphanous',
    'serene',
    'majestic',
    'captivating',
    'impeccable',
    'exuberant',
    'effervescent',
    'labyrinthine',
    'enthralling',
    'enigmatic',
    'audacious',
  ];

  const nouns = [
    'cathedral',
    'comet',
    'compass',
    'constellation',
    'dandelion',
    'eclipse',
    'elegy',
    'firefly',
    'fractal',
    'galaxy',
    'gargoyle',
    'geyser',
    'hieroglyph',
    'hurricane',
    'kaleidoscope',
    'magician',
    'meteorite',
    'monastery',
    'mural',
    'nocturne',
    'nomad',
    'oasis',
    'paradox',
    'pebble',
    'phoenix',
    'pilgrim',
    'prism',
    'quicksand',
    'rainstorm',
    'reflection',
    'relic',
    'rhapsody',
    'sandstone',
    'savannah',
    'skyscraper',
    'sonnet',
    'spectacle',
    'sphinx',
    'staircase',
    'symphony',
    'tapestry',
    'tornado',
    'trailblazer',
    'tremor',
    'twilight',
    'whimsy',
    'willow',
    'windmill',
    'wolf',
    'zenith',
  ];

  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];

  return adjective + noun;
}

export function generateRandomColor() {
  return '#' + Math.floor(Math.random() * 0xffffff).toString(16);
}

export function generateUniqueId() {
  return Math.random().toString(36).slice(2);
}
